"""Shared utility functions for image processing and VLM response parsing."""
from __future__ import annotations
import base64
from io import BytesIO
from typing import Any
from PIL import Image

def pil_to_b64(img: Image.Image) -> str:
    """
    Convert a PIL Image to a base64 encoded PNG string.
    
    Args:
        img: The PIL Image to convert.
        
    Returns:
        A base64 encoded string of the image.
    """
    buf = BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()

def extract_vlm_text(content: Any) -> str:
    """
    Extract and clean text from various VLM response formats.
    
    Handles:
    - Raw strings
    - Lists of content chunks (with 'text' attribute or key)
    - Markdown code blocks
    - Common invalid JSON escape sequences
    
    Args:
        content: The raw content from the VLM response.
        
    Returns:
        The cleaned and extracted text string.
    """
    if content is None:
        return ""
    
    text = ""
    if isinstance(content, str):
        text = content.strip()
    elif isinstance(content, list):
        texts = []
        for chunk in content:
            if hasattr(chunk, "text") and chunk.text:
                texts.append(chunk.text)
            elif isinstance(chunk, dict):
                texts.append(chunk.get("text", ""))
        text = "".join(texts).strip()
    else:
        text = str(content).strip()

    # Cleaning Markdown code blocks (e.g., ```json ... ```)
    if text.startswith("```"):
        lines = text.splitlines()
        if len(lines) > 2:
            content_lines = []
            for line in lines[1:]:
                if line.strip() == "```":
                    break
                content_lines.append(line)
            text = "\n".join(content_lines).strip()
    
    # Cleaning invalid JSON escape sequences (often generated by LLMs)
    # Escaped single quote \' is not allowed in standard JSON.
    text = text.replace("\\'", "'")
    
    return text
