"""Shared utility functions for image processing and VLM response parsing."""
from __future__ import annotations
import base64
from io import BytesIO
from typing import Any
from PIL import Image
from .console import console as _console
DEBUG: bool = False


def dbg(msg: str) -> None:
    """Print a raw debug message — only when DEBUG is enabled."""
    if DEBUG:
        _console.print(f"  [dim]{msg}[/dim]")


def dbg_frame(model: str, clip: str, frame: str, n: int) -> None:
    if DEBUG:
        _console.print(f"\n  [bold cyan]◆[/bold cyan] [bold]{model}[/bold] [dim]·[/dim] [white]{clip}/{frame}[/white] [dim]·[/dim] [cyan]N={n}[/cyan]")


def dbg_infer(latency: float, prompt_tok: int | None, completion_tok: int | None, chars: int) -> None:
    if DEBUG:
        tok = f"{prompt_tok or '?'} → {completion_tok or '?'} tokens"
        _console.print(f"    [green]✓ infer[/green]    [yellow]{latency:.1f}s[/yellow] · [dim]{tok} · {chars} chars[/dim]")


def dbg_parse(success: bool, got: int, expected: int, error: str | None) -> None:
    if DEBUG:
        if success:
            _console.print(f"    [green]✓ parse[/green]    [dim]{got}/{expected} frames[/dim]")
        else:
            detail = f" — {error}" if error else ""
            _console.print(f"    [red]✗ parse[/red]    [dim]{got}/{expected} frames{detail}[/dim]")


def dbg_judge(completeness: float, richness: float, spatial: float, overall: float) -> None:
    if DEBUG:
        color = "green" if overall >= 0.7 else ("yellow" if overall >= 0.4 else "red")
        _console.print(
            f"    [green]✓ judge[/green]    "
            f"[dim]completeness=[/dim][white]{completeness:.2f}[/white]  "
            f"[dim]richness=[/dim][white]{richness:.2f}[/white]  "
            f"[dim]spatial=[/dim][white]{spatial:.2f}[/white]  "
            f"[dim]overall=[/dim][{color}]{overall:.2f}[/{color}]"
        )


def dbg_judge_skip(reason: str) -> None:
    if DEBUG:
        _console.print(f"    [dim]─ judge    skipped ({reason})[/dim]")


def dbg_judge_error(error: str) -> None:
    if DEBUG:
        _console.print(f"    [red]✗ judge[/red]    [dim]{error}[/dim]")


def dbg_retry(attempt: int, max_retries: int, delay: int, error: str) -> None:
    if DEBUG:
        _console.print(f"    [yellow]⟳ retry[/yellow]    [dim]attempt {attempt}/{max_retries} in {delay}s — {error}[/dim]")

def pil_to_b64(img: Image.Image) -> str:
    """
    Convert a PIL Image to a base64 encoded PNG string.
    
    Args:
        img: The PIL Image to convert.
        
    Returns:
        A base64 encoded string of the image.
    """
    buf = BytesIO()
    img.save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode()

def extract_vlm_text(content: Any) -> str:
    """
    Extract and clean text from various VLM response formats.
    
    Handles:
    - Raw strings
    - Lists of content chunks (with 'text' attribute or key)
    - Markdown code blocks
    - Common invalid JSON escape sequences
    
    Args:
        content: The raw content from the VLM response.
        
    Returns:
        The cleaned and extracted text string.
    """
    if content is None:
        return ""
    
    text = ""
    if isinstance(content, str):
        text = content.strip()
    elif isinstance(content, list):
        texts = []
        for chunk in content:
            if hasattr(chunk, "text") and chunk.text:
                texts.append(chunk.text)
            elif isinstance(chunk, dict):
                texts.append(chunk.get("text", ""))
        text = "".join(texts).strip()
    else:
        text = str(content).strip()

    # Cleaning Markdown code blocks (e.g., ```json ... ```)
    if text.startswith("```"):
        lines = text.splitlines()
        if len(lines) > 2:
            content_lines = []
            for line in lines[1:]:
                if line.strip() == "```":
                    break
                content_lines.append(line)
            text = "\n".join(content_lines).strip()
    
    # Cleaning invalid JSON escape sequences (often generated by LLMs)
    # Escaped single quote \' is not allowed in standard JSON.
    text = text.replace("\\'", "'")
    
    return text
